services:
    front:
        depends_on:
            - socket-server
        build:
            context: ./front
            target: dev
        container_name: front
        hostname: front
        networks:
            - mynet
        ports:
            - 3000:3000
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000']
            interval: 10s
            timeout: 5s
            retries: 5

    back:
        depends_on:
            db:
                condition: service_healthy
        build:
            context: ./back
            target: dev
        container_name: back
        hostname: back
        networks:
            - mynet
        ports:
            - 8001:8001
        environment:
            - DB_HOST=${DB_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - DB_PORT=${DB_PORT}
            - TOKEN_TTL=${TOKEN_TTL}
            - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
            - FRONT_URL=${FRONT_URL}

    socket-server:
        restart: always
        build:
            context: ./socket-server
            target: dev
        develop:
            watch:
                - action: rebuild
                  path: ./socket-server
                  files:
                      - ./socket-server/**/*.go
                      - ./socket-server/go.mod
                      - ./socket-server/go.sum
        container_name: socket-server
        hostname: socket-server
        networks:
            - mynet
        ports:
            - 5000:5000

    db:
        image: postgres:16-alpine
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}',
                ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        container_name: db
        hostname: db
        networks:
            - mynet
        ports:
            - 5431:5432
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

    cypress:
        image: cypress/included:13.15.0
        container_name: cypress
        depends_on:
            front:
                condition: service_healthy
        networks:
            - mynet
        working_dir: /e2e
        volumes:
            - ./e2e:/e2e
        entrypoint: ['npx', 'cypress', 'run']

volumes:
    db:

networks:
    mynet:
        driver: bridge
