##################################
#### COMPOSE DOCUMENTATION 🐳 ####
##################################
### Run e2e tests with this compose file
# $ docker compose -f docker-compose.test.yml up --abort-on-container-exit

services:
    front-test:
        depends_on:
            - socket-server-test
        build:
            context: ./front
            target: dev
        ports:
            - 3000:3000
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://front-test:3000']
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            - NUXT_PUBLIC_REST_API_URL=http://rest-server-test:8001/api
            - NUXT_PUBLIC_SOCKET_SERVER_URL=ws://socket-server-test:5000/ws
        networks:
            - test_net

    rest-server-test:
        depends_on:
            db-test:
                condition: service_healthy
        build:
            context: ./rest-server
            target: dev
        environment:
            - DB_HOST=db-test
            - POSTGRES_USER=test_db_user
            - POSTGRES_PASSWORD=test_db_password
            - POSTGRES_DB=test_db
            - DB_PORT=5432
            - TOKEN_TTL=test_token_ttl
            - JWT_PRIVATE_KEY=test_jwt_private_key
            - FRONT_URL=http://front-test:3000
        networks:
            - test_net
        ports:
            - 8001:8001

    socket-server-test:
        restart: always
        build:
            context: ./socket-server
            target: dev
        networks:
            - test_net

    db-test:
        image: postgres:16-alpine
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U test_db_user -d test_db']
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        environment:
            - POSTGRES_USER=test_db_user
            - POSTGRES_PASSWORD=test_db_password
            - POSTGRES_DB=test_db
        tmpfs:
            - /var/lib/postgresql/data # In-memory storage for database data
        networks:
            - test_net
        ports:
            - 5431:5432

    cypress:
        image: cypress/included:13.15.0
        depends_on:
            - front-test
            - rest-server-test
            - db-test
            - socket-server-test
        working_dir: /e2e
        volumes:
            - ./e2e:/e2e
        entrypoint: ['npm', 'run', 'cy']
        networks:
            - test_net
        environment:
            - BASE_URL=http://front-test:3000

networks:
    test_net:
        driver: bridge
