#######################################
#### COMPOSE PROD DOCUMENTATION 🐳 ####
#######################################
### Run in production: ###
# $ ssh root@165.22.119.201
# $ cd chess_app/
# $ docker pull colinfaivre/chess_front_prod:latest
# $ docker pull colinfaivre/chess_rest_server_prod:latest
# $ docker compose -f docker-compose.prod.yml up --detach --build
# $ docker compose -f docker-compose.prod.yml down
### Execute a command inside a running compose service
# $ docker compose -f docker-compose.prod.yml exec db bash
# db:/# psql -h localhost -d chess -U chess -p 5432
# chess=# \dt

# @TODO Use docker swarm instead of compose in production

services:
    nginx:
        image: nginx:alpine
        restart: always
        depends_on:
            - front
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt

    front:
        image: colinfaivre/chess_front_prod
        restart: always
        depends_on:
            - socket-server
        ports:
            - '3000:3000'
        environment:
            - NUXT_PUBLIC_REST_API_URL=https://nuxtchess.com/api
            - NUXT_PUBLIC_SOCKET_SERVER_URL=wss://nuxtchess.com/ws

    rest-server:
        image: colinfaivre/chess_rest_server_prod
        restart: always
        depends_on:
            db:
                condition: service_healthy
        ports:
            - 8001:8001
        environment:
            - DB_HOST=${DB_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - DB_PORT=${DB_PORT}
            - TOKEN_TTL=${TOKEN_TTL}
            - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
            - GIN_MODE=release
            - FRONT_URL=https://nuxtchess.com

    db:
        image: postgres:16-alpine
        restart: always
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}',
                ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        ports:
            - 5431:5432
            - 8080:8080
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

    socket-server:
        image: colinfaivre/chess_socket_server_prod
        restart: always
        ports:
            - 5000:5000

volumes:
    db:
