version: "3.8"

services:
  express:
    container_name: express_container
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - db
  db:
    image: mongo:3
    container_name: mongo_container
    restart: always
    env_file: ./.env
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PWD
    volumes:
      - ./db/:/data/db