name: Build and deploy

on:
    push:
        branches:
            - main # also triggered by a merge into main
    pull_request:

env:
    REGISTRY: 'colinfaivre'
    FRONT_IMAGE_NAME: 'chess_front_prod'
    BACK_IMAGE_NAME: 'chess_rest_server_prod'

jobs:
    build-push-images:
        name: Build images
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  install: true

            - name: Build dev front image
              uses: docker/build-push-action@v6
              with:
                  context: '{{defaultContext}}:apps/front'
                  target: dev
                  push: false
                  load: true
                  tags: ${{ github.run_id }}

            - name: Check front format/linting/typescript/unit-testing in Docker
              run: |
                  docker run --rm ${{ github.run_id }} sh -c "\
                  npm run format:check && \
                  npm run lint && \
                  npm run postinstall && \
                  npm run ts:check && \
                  npm run test:unit"

            - name: Build dev rest-server image
              uses: docker/build-push-action@v6
              with:
                  context: '{{defaultContext}}:apps/rest-server'
                  target: dev
                  push: false
                  load: true # Export to Docker Engine rather than pushing to a registry
                  tags: ${{ github.run_id }}

            - name: Check rest-server unit-testing in Docker Engine
              run: |
                  docker run --rm ${{ github.run_id }} ginkgo -r

            - name: Build dev socket-server image
              uses: docker/build-push-action@v6
              with:
                  context: '{{defaultContext}}:apps/socket-server'
                  target: dev
                  push: false
                  load: true # Export to Docker Engine rather than pushing to a registry
                  tags: ${{ github.run_id }}

            # - name: Check socket-server unit-testing in Docker Engine
            #   run: |
            #       docker run --rm ${{ github.run_id }} ginkgo -r

    e2e-tests:
        name: Run E2E Tests
        runs-on: ubuntu-latest
        needs: build-push-images
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Docker Compose
              run: sudo apt-get install docker-compose

            - name: Run E2E tests
              run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

    push-images:
        name: Push images to Docker Hub
        runs-on: ubuntu-latest
        needs: e2e-tests
        if: ${{ success() && github.event_name != 'pull_request' }}
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and push prod front image to Docker Hub
              uses: docker/build-push-action@v6
              with:
                  context: '{{defaultContext}}:apps/front'
                  target: prod
                  push: true
                  tags: colinfaivre/chess_front_prod

            - name: Build and push prod rest-server image to Docker Hub
              uses: docker/build-push-action@v6
              with:
                  context: '{{defaultContext}}:apps/rest-server'
                  target: prod
                  push: true
                  tags: colinfaivre/chess_rest_server_prod

            - name: Build and push prod socket-server image to Docker Hub
              uses: docker/build-push-action@v6
              with:
                  context: '{{defaultContext}}:apps/socket-server'
                  target: prod
                  push: true
                  tags: colinfaivre/chess_socket_server_prod

    deploy:
        if: ${{ github.event_name != 'pull_request' }}
        runs-on: ubuntu-latest
        needs: push-images
        steps:
            - name: Deploy to Digital Ocean droplet via SSH action
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.DROPLET_HOST_IP }}
                  username: ${{ secrets.DROPLET_USERNAME }}
                  key: ${{ secrets.DROPLET_SSH_KEY }}
                  script: |
                      echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
                      docker pull colinfaivre/chess_front_prod
                      docker pull colinfaivre/chess_rest_server_prod
                      docker pull colinfaivre/chess_socket_server_prod

                      cd ~/chess
                      git fetch origin main
                      git reset --hard origin/main

                      docker compose -f docker-compose.prod.yml down
                      docker compose -f docker-compose.prod.yml up --detach
                      docker image prune -f
